graph TD
Client --> NFSensorAPI.dll
    NFSensorAPI.dll --> NFDevicBase.dll
    NFSensorAPI.dll --> NFBaseTypes.dll
    NFSensorAPI.dll --> NFEval.dll
    NFSensorAPI.dll --> NFEvalLogger.dll
    NFSensorAPI.dll --> Plugins([\Devices]) 
    Plugins --> NFHicosSensor.dll
    Plugins --> NFMsprint128Sensor.dll